/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!**/node_modules/**',
    // Ignore files generated by ANTLR.
    '!src/lang/**'
  ],
  modulePathIgnorePatterns: [
    'dist'
  ]
};
